# Generated by Django 2.0.3 on 2018-05-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='bid_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
