# Generated by Django 2.0.3 on 2018-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_yn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
