# Generated by Django 2.0.3 on 2018-06-11 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20180608_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deadline',
            new_name='deadline_at',
        ),
        migrations.AddField(
            model_name='card',
            name='meet_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
